modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/Mrbysco/RoughlyEnoughProfessions/issues"
license = "MIT"

[[mods]]
modId = "roughlyenoughprofessions"
version = "${file.jarVersion}"
displayName = "Roughly Enough Professions"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/Roughly-Enough-Professions"
authors = "Mrbysco, ShyNieke"
description = '''
Adds info about professions to REI
'''
[[dependencies.roughlyenoughprofessions]]
modId = "roughlyenoughitems"
mandatory = true
versionRange = "[11.0.597,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.roughlyenoughprofessions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "CLIENT"